---
- hosts: 127.0.0.1
  become_method: runas
  become_user: Administrator
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: basic
  pre_tasks:
   - include: pre-tasks/init.yml
   - include: pre-tasks/system.yml
  tasks:
   - include: tasks/packages.yml
  post_tasks:
   - name: Reboot
     win_reboot: 
